# Generated by Django 5.1.2 on 2024-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_usersettings_delete_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='preferred_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
